AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# テスト用の簡易モデルなのでドキュメント不要
Style/Documentation:
  Exclude:
    - "spec/**/*"

# ブロック長は指定しない
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
